version: 0.2

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - docker build -t myapp .
      - docker tag myapp:latest $ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/myapp:latest

  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/myapp:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
